apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-stellar
  annotations:
    # Add supports for Halo App Store
    # https://www.halo.run/store/apps/app-KxJeQ
    "store.halo.run/app-id": "app-KxJeQ"
spec:
  customTemplates:
    page:
      - name: 专题分类模板
        description:
        screenshot:
        file: category_topic.html
    post:
      - name: 专题模板
        description:
        screenshot:
        file: topic.html
  displayName: Stellar
  author:
    name: 困困鱼
    website: "https://github.com/chengzhongxue"
  description: 内置文档系统的简约商务风Halo主题，支持大量的标签组件和动态数据组件。
  logo: "/themes/theme-stellar/assets/img/icon.svg"
  homepage: "https://www.halo.run/store/apps/app-KxJeQ"
  repo: "https://github.com/chengzhongxue/halo-theme-stellar"
  issues: "https://github.com/chengzhongxue/halo-theme-stellar/issues"
  settingName: "theme-stellar-setting"
  configMapName: "theme-stellar-configMap"
  version: "1.0.1"
  requires: ">=2.20.0"
  license:
    - name: "MIT license"
      url: "https://github.com/chengzhongxue/halo-theme-stellar/blob/main/LICENSE"
  
